name: super-linter
on: push

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run super-linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


######################################
# Super-Linter configuration file
######################################

# Validate the entire codebase (not just diffs)
# VALIDATE_ALL_CODEBASE: true

# # Enable only the necessary linters for your stack
# VALIDATE_HTML: true
# VALIDATE_CSS: true
# VALIDATE_JAVASCRIPT_ES: true
# VALIDATE_JSON: true

# # Disable unnecessary linters
# VALIDATE_BASH: false
# VALIDATE_GITHUB_ACTIONS: false
# VALIDATE_PYTHON: false
# VALIDATE_TYPESCRIPT_ES: false
# VALIDATE_YAML: false
# VALIDATE_MARKDOWN: false
# VALIDATE_DOCKERFILE: false
# VALIDATE_XML: false

# # Set the location of your custom rules (keep as root for now)
# LINTER_RULES_PATH: /

# # Optional: Max linter timeout in seconds (default is 1800 = 30min)
# MAXIMUM_FILE_LINT_TIME: 300
